version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tech
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tech
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
